

text = """
4
X.........
..........
.......X..
.....X....
......X...
..........
.........X
..X.......
..........
.........X
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
..........
....X.....
..........
..........
..........
..........
..........
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
XXXXXXXXXX
"""

board = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
         [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
         [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
         [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
         [1, 2, 3, 4, 5, 5, 4, 3, 2, 1],
         [1, 2, 3, 4, 4, 4, 4, 3, 2, 1],
         [1, 2, 3, 3, 3, 3, 3, 3, 2, 1],
         [1, 2, 2, 2, 2, 2, 2, 2, 2, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

stopword = ""
while True:
    line = raw_input()
    if line.strip() == stopword:
        break
    text += "%s\n" % line
print (text)


# for i in range(numInputs):
#     new_board = []
#     for i in range(9):
#         new_board.append()
# for i in range(numInputs * 4):
#     test
